# Generated by Django 2.0.5 on 2018-05-11 10:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rungtynes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komanda1', models.CharField(max_length=100)),
                ('komanda2', models.CharField(max_length=100)),
                ('kofas1', models.FloatField(default=1)),
                ('kofas2', models.FloatField(default=1)),
                ('kofasx', models.FloatField(default=1)),
                ('data', models.DateTimeField(default=datetime.datetime(2018, 5, 11, 13, 25, 10, 890932))),
                ('prasidejo', models.BooleanField(default=False)),
                ('baigtis', models.CharField(default='NA', max_length=2)),
                ('rezultatas', models.CharField(default=' : ', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Stavke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasirinkimas', models.CharField(default='', max_length=2)),
                ('laimeta', models.BooleanField(default=False)),
                ('rungtynes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rungtynes', to='apas.Rungtynes', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zaidejas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskai', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zaidejas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='stavke',
            name='zaidejas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zaidejas', to='apas.Zaidejas'),
        ),
    ]
